# Used when Blog and Drone are on separate servers
---
ci:
  hosts:
    ci-remote:
      ansible_ssh_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_host: "{{ lookup('env', 'SERVER_DRONE_IP') }}"
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
blog:
  hosts:
    blog-remote:
      ansible_ssh_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_host: "{{ lookup('env', 'SERVER_BLOG_IP') }}"
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
