#!/usr/bin/env bash
set -e
set -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CMD=${@:-ansible-playbook-wrapper}

source "${DIR}/.env"

SERVER_IP=${SERVER_IP:-}
DO_CI_SERVER_IP=${DO_CI_SERVER_IP:-}
DO_BLOG_SERVER_IP=${DO_BLOG_SERVER_IP:-}

LE_EMAIL=${LE_EMAIL:-}

DRONE_HOST=${DRONE_HOST:-}
DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT:-}
DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET:-}
DRONE_SECRET=${DRONE_SECRET:-}

if [[ -z "${DO_SERVER_IP}" ]] &&
   [[ -z "${DO_CI_SERVER_IP}" ]] &&
   [[ -z "${DO_BLOG_SERVER_IP}" ]]; then
    printf "You must create a .env file and define either "
    printf "DO_SERVER_IP or both "
    printf "DO_CI_SERVER_IP and DO_BLOG_SERVER_IP"
    printf "\n"

    exit 1
fi

if [[ ! -z "${DO_SERVER_IP}" ]]; then
    INVENTORY=/etc/ansible/hosts-joined.yml
else
    INVENTORY=/etc/ansible/hosts.yml
fi

docker container run -it --rm \
    -e SSH_AUTH_SOCK=/ssh-agent \
    -e INVENTORY=${INVENTORY} \
    -e PLAYBOOK=/etc/ansible/playbook.yml \
    -e ANSIBLE_HOST_KEY_CHECKING=false \
    -e DO_SERVER_IP=${DO_SERVER_IP} \
    -e DO_CI_SERVER_IP=${DO_CI_SERVER_IP} \
    -e DO_BLOG_SERVER_IP=${DO_BLOG_SERVER_IP} \
    -e LE_EMAIL=${LE_EMAIL} \
    -e DRONE_HOST=${DRONE_HOST} \
    -e DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT} \
    -e DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET} \
    -e DRONE_SECRET=${DRONE_SECRET} \
    -v ${SSH_AUTH_SOCK}:/ssh-agent:ro \
    -v ${PWD}:/etc/ansible \
    -v ${HOME}/.ssh/id_rsa_digitalocean:/root/.ssh/id_rsa \
    -v ${HOME}/.ssh/id_rsa_digitalocean.pub:/root/.ssh/id_rsa.pub \
    williamyeh/ansible:ubuntu16.04-onbuild bash -c "${CMD}"
